#!/usr/bin/env python3
"""xizhi.py sync 组件生成冒烟（离线）——模板输出契约 + 幂等 + 安全红线。

钉死：react/solid JSX 属性显式映射（只改名不改值、未知属性原样）、
vue/svelte 原样包裹、svg 复制带溯源头、生成器纯函数幂等、
harmonyos 拒绝、投毒 SVG 拒绝生成。
跑法：python3 -m pytest tests -q
"""
import io
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest import mock

os.environ.setdefault("XIZHI_CACHE", tempfile.mkdtemp(prefix="xizhi-cache-test-"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

import xizhi  # noqa: E402

SVG_FIXTURE = (b'<svg xmlns="http://www.w3.org/2000/svg" class="lucide" '
               b'stroke="currentColor" stroke-width="2">'
               b'<rect stroke-width="2" fill-rule="evenodd" fill="currentColor"/>'
               b'<rect data-foo="1"/></svg>')


def _sync_args(framework, out_dir, **kw):
    fields = dict(set="lucide", name="house", out=str(out_dir), framework=framework,
                  style=None, size=None, fill=None, variant=None, weight=None, wght=None,
                  version=None, format=None, color=None, sprite=False, refresh=False,
                  dir=None)
    fields.update(kw)
    return SimpleNamespace(**fields)


def _run_sync(framework, **kw):
    out_dir = Path(tempfile.mkdtemp(prefix="xizhi-sync-"))
    set_id = kw.pop("set", "lucide")
    name = kw.pop("name", "house")
    with mock.patch.object(xizhi, "http_get", return_value=SVG_FIXTURE), \
            mock.patch("sys.stdout", new_callable=io.StringIO) as out, \
            mock.patch("sys.stderr", new_callable=io.StringIO) as err:
        rc = xizhi.cmd_sync(_sync_args(framework, out_dir, set=set_id, name=name, **kw))
    return rc, out_dir, out.getvalue(), err.getvalue()


class TestSyncReact(unittest.TestCase):
    def test_component_contract(self):
        rc, out_dir, outv, errv = _run_sync("react")
        self.assertEqual(rc, 0)
        f = out_dir / "XizhiLucideHouse.tsx"
        self.assertTrue(f.is_file())
        text = f.read_text(encoding="utf-8")
        self.assertIn("// generated by xizhi (lucide:house)", text)  # 幂等标记
        self.assertIn("export function XizhiLucideHouse(props: SVGProps<SVGSVGElement>)", text)
        self.assertIn('className="lucide"', text)  # class → className（仅改名）
        self.assertEqual(text.count('strokeWidth="2"'), 2)  # 根标签 + 嵌套 rect，值不动
        self.assertIn('fillRule="evenodd"', text)
        self.assertIn('data-foo="1"', text)  # 未映射属性原样保留
        self.assertIn('fill="currentColor"', text)  # 属性值绝不改写
        self.assertIn("{...props}", text)
        self.assertIn("import { XizhiLucideHouse }", outv)  # 回传 import 语句

    def test_pure_function_idempotent(self):
        _, out1, _, _ = _run_sync("react")
        _, out2, _, _ = _run_sync("react")
        self.assertEqual((out1 / "XizhiLucideHouse.tsx").read_bytes(),
                         (out2 / "XizhiLucideHouse.tsx").read_bytes())

    def test_batch_names_generate_components(self):
        rc, out_dir, outv, errv = _run_sync("react", name="house, bell")
        self.assertEqual(rc, 0)
        self.assertTrue((out_dir / "XizhiLucideHouse.tsx").is_file())
        self.assertTrue((out_dir / "XizhiLucideBell.tsx").is_file())
        self.assertIn("2 wrote", outv)


class TestSyncSolid(unittest.TestCase):
    def test_class_stays_and_kebab_renamed(self):
        rc, out_dir, _, errv = _run_sync("solid")
        self.assertEqual(rc, 0)
        text = (out_dir / "XizhiLucideHouse.tsx").read_text(encoding="utf-8")
        self.assertIn('class="lucide"', text)  # solid 用 class
        self.assertIn('strokeWidth="2"', text)
        self.assertNotIn("className", text)


class TestSyncVueSvelte(unittest.TestCase):
    def test_vue_wraps_template_keeps_kebab(self):
        rc, out_dir, _, errv = _run_sync("vue")
        self.assertEqual(rc, 0)
        text = (out_dir / "XizhiLucideHouse.vue").read_text(encoding="utf-8")
        self.assertIn("<!-- generated by xizhi (lucide:house)", text)
        self.assertIn("<template>", text)
        self.assertIn('stroke-width="2"', text)  # vue 模板原样吃连字符属性
        self.assertNotIn("className", text)

    def test_svelte_raw_markup(self):
        rc, out_dir, _, errv = _run_sync("svelte")
        self.assertEqual(rc, 0)
        text = (out_dir / "XizhiLucideHouse.svelte").read_text(encoding="utf-8")
        self.assertIn("<!-- generated by xizhi (lucide:house)", text)
        self.assertIn("<svg", text)
        self.assertIn("</svg>", text)


class TestSyncSvgCopy(unittest.TestCase):
    def test_svg_framework_writes_raw_with_provenance(self):
        rc, out_dir, _, errv = _run_sync("svg")
        self.assertEqual(rc, 0)
        content = (out_dir / "house.svg").read_bytes()
        self.assertTrue(content.startswith(b"<!-- xizhi: lucide:house via "))
        self.assertIn(b'stroke-width="2"', content)  # 原样


class TestSyncGuards(unittest.TestCase):
    def test_harmonyos_rejected(self):
        with self.assertRaises(SystemExit) as cm:
            _run_sync("react", set="harmonyos")
        self.assertIn("harmonyos", str(cm.exception))

    def test_unknown_framework_rejected(self):
        with self.assertRaises(SystemExit):
            _run_sync("angular")

    def test_poisoned_svg_rejected_no_component(self):
        out_dir = Path(tempfile.mkdtemp(prefix="xizhi-sync-"))
        payload = b'<svg><script>alert(1)</script></svg>'
        with mock.patch.object(xizhi, "http_get", return_value=payload), \
                mock.patch("sys.stdout", new_callable=io.StringIO) as out, \
                mock.patch("sys.stderr", new_callable=io.StringIO) as err:
            rc = xizhi.cmd_sync(_sync_args("react", out_dir))
        errv = err.getvalue()
        self.assertEqual(rc, 1)
        self.assertIn("[security]", errv)
        self.assertEqual(list(out_dir.iterdir()), [])  # 不落任何组件

    def test_fetch_failure_counted_batch_continues(self):
        out_dir = Path(tempfile.mkdtemp(prefix="xizhi-sync-"))

        def flaky(url, binary=False, timeout=30):
            if "bell" in url:
                raise SystemExit("[error] HTTP 404")
            return SVG_FIXTURE

        with mock.patch.object(xizhi, "http_get", side_effect=flaky), \
                mock.patch("sys.stdout", new_callable=io.StringIO) as out, \
                mock.patch("sys.stderr", new_callable=io.StringIO) as err:
            rc = xizhi.cmd_sync(_sync_args("react", out_dir, name="house,bell"))
        errv = err.getvalue()
        self.assertEqual(rc, 1)
        self.assertIn("[fail] bell", errv)
        self.assertTrue((out_dir / "XizhiLucideHouse.tsx").is_file())



class TestSyncGateFixes(unittest.TestCase):
    """门禁修复回归：模板花括号注入拦截 / 变体校验 / 根标签定位 / 本地降级复用。"""

    BRACED = b"<svg><desc>{fetch(`https://evil`)}</desc><path d='M0'/></svg>"

    def test_braces_rejected_for_template_frameworks(self):
        out_dir = Path(tempfile.mkdtemp(prefix="xizhi-sync-"))
        with mock.patch.object(xizhi, "http_get", return_value=self.BRACED), \
                mock.patch("sys.stdout", new_callable=io.StringIO) as out, \
                mock.patch("sys.stderr", new_callable=io.StringIO) as err:
            rc = xizhi.cmd_sync(_sync_args("react", out_dir))
        self.assertEqual(rc, 1)
        self.assertIn("[security]", err.getvalue())
        self.assertEqual(list(out_dir.iterdir()), [])  # 不落任何组件

    def test_braces_allowed_for_svg_copy(self):
        out_dir = Path(tempfile.mkdtemp(prefix="xizhi-sync-"))
        with mock.patch.object(xizhi, "http_get", return_value=self.BRACED), \
                mock.patch("sys.stdout", new_callable=io.StringIO), \
                mock.patch("sys.stderr", new_callable=io.StringIO):
            rc = xizhi.cmd_sync(_sync_args("svg", out_dir))
        self.assertEqual(rc, 0)  # 原样资产无模板上下文，花括号无害
        self.assertEqual(len(list(out_dir.iterdir())), 1)

    def test_security_abort_stops_multi_icon_batch(self):
        # 镜像 fetch 的 evil,clean 用例：红线中止后 clean 不落盘（A1 残缺钉）
        out_dir = Path(tempfile.mkdtemp(prefix="xizhi-sync-"))
        payloads = {"house": SVG_FIXTURE, "evil": b"<svg><script>alert(1)</script></svg>"}

        def getter(url, binary=False, timeout=30):
            return payloads[url.rsplit("/", 1)[1].split(".")[0]]

        with mock.patch.object(xizhi, "http_get", side_effect=getter), \
                mock.patch("sys.stdout", new_callable=io.StringIO) as out, \
                mock.patch("sys.stderr", new_callable=io.StringIO) as err:
            rc = xizhi.cmd_sync(_sync_args("react", out_dir, name="house,evil"))
        self.assertEqual(rc, 1)
        self.assertIn("[security]", err.getvalue())
        self.assertIn("安全红线中止：0 failed, 1 wrote", out.getvalue())
        self.assertFalse((out_dir / "XizhiLucideEvil.tsx").exists())

    def test_illegal_variant_exits(self):
        with self.assertRaises(SystemExit) as cm:
            _run_sync("react", set="tabler", style="bogus")
        self.assertIn("非法", str(cm.exception))

    def test_illegal_version_exits_at_entry(self):
        # 配置错误（无版本槽位通道传 --version）在入口中止，不逐条 [fail]
        with self.assertRaises(SystemExit) as cm:
            _run_sync("react", set="heroicons", version="1.0.0")
        self.assertIn("--version", str(cm.exception))

    def test_root_spread_handles_gt_in_attr(self):
        svg = b'<svg title="a>b" class="x"><path/></svg>'
        out = xizhi._jsx_root_spread(svg)
        self.assertIn(b'<svg title="a>b" class="x" {...props}>', out)
        self.assertTrue(out.endswith(b"<path/></svg>"))

    def test_marker_injection_sanitized(self):
        # 安全复审 N1：name 含 --> 与换行时，marker 消毒，产物无可执行注入块
        rc, out_dir, _, errv = _run_sync("vue", name='house--><script>alert(1)</script><!--')
        self.assertEqual(rc, 0)  # 消毒放行，产物无害
        text = next(out_dir.glob("*.vue")).read_text(encoding="utf-8")
        self.assertEqual(text.count("-->"), 1)  # 恰一个注释终止（--> 被消毒为 __>）
        # 注入的 <script> 被困在注释体内（终止符之后），不构成 SFC 顶层脚本块
        self.assertLess(text.index("<script>"), text.index("-->"))

        rc, out_dir, _, errv = _run_sync("react", name='house\nimport x from "evil"\n//')
        self.assertEqual(rc, 0)
        text = next(out_dir.glob("*.tsx")).read_text(encoding="utf-8")
        # 换行被剥离：注入文本困在首行 // 注释内，没有独立代码行
        self.assertTrue(text.splitlines()[0].startswith("// generated by xizhi"))
        self.assertFalse(any(l.strip().startswith("import x from") for l in text.splitlines()))

    def test_sync_iconify_local_fallback(self):
        root = Path(tempfile.mkdtemp(prefix="xizhi-sync-local-"))
        pkg = root / "node_modules" / "@iconify-json" / "lucide"
        pkg.mkdir(parents=True)
        (pkg / "icons.json").write_text(json.dumps(
            {"icons": {"house": {"body": "<p d='L'/>"}}, "width": 24, "height": 24}),
            encoding="utf-8")
        old = os.getcwd()
        os.chdir(root)
        try:
            out_dir = Path(tempfile.mkdtemp(prefix="xizhi-sync-out-"))
            with mock.patch.object(xizhi, "http_get",
                                   side_effect=SystemExit("[error] offline")), \
                    mock.patch("sys.stdout", new_callable=io.StringIO), \
                    mock.patch("sys.stderr", new_callable=io.StringIO):
                rc = xizhi.cmd_sync(_sync_args("react", out_dir,
                                               set="iconify", name="lucide:house"))
        finally:
            os.chdir(old)
        self.assertEqual(rc, 0)
        self.assertTrue((out_dir / "XizhiIconifyLucideHouse.tsx").is_file())


if __name__ == "__main__":
    unittest.main()

